services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: plutodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      DATABASE_URL: postgresql://postgres:user@db:5433/plutodb

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: plutodb
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
